routes/web.php
<?php

// Сайт
Route::get('/', 'IndexController@index')->name('start');
Route::resource('posts', 'PostController')
     ->only(['index', 'show']);
Route::resource('categories', 'CategoryController')
     ->only(['index', 'show']);

// Админпанель
Route::group([
    'prefix'     => 'admin',
    'middleware' => 'auth',
    'namespace'  => 'Admin',
    'as'         => 'admin.',
], function () {
    Route::get('/', 'IndexController@index')->name('index');

    Route::get('posts', 'IndexController@posts')->name('posts.index');
    Route::get('posts/fetch', 'PostController@index');
    Route::resource('posts', 'PostController')
         ->only(['store', 'update', 'destroy']);

    Route::get('categories', 'IndexController@categories')->name('categories.index');
    Route::get('categories/fetch', 'CategoryController@index');
    Route::resource('categories', 'CategoryController')
         ->only(['store', 'update', 'destroy']);
});

// Авторизация
Auth::routes();
Route::match(['get', 'post'], '/register', function () {
    return redirect()->route('start');
})->name('register');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['title'];

    /**
     * Публикации категории
     * Связь many-to-many
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;

class CategoryController extends Controller
{

    /**
     * Получаем все категории
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        // Получаем категории
        $categories = Category::all();

        // Ответ
        return response()->json(['categories' => $categories]);
    }

    /**
     * Создаем запись
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        // Создаем запись
        $category = Category::create(['title' => $request->input('title')]);

        // Ответ
        return response()->json(['category' => $category]);
    }

    /**
     * Обновляем запись
     *
     * @param \Illuminate\Http\Request $request
     * @param                          $id
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $id)
    {
        // Обновляем данные
        Category::find($id)->update(['title' => $request->input('title')]);

        // Ответ
        return response()->json(['category' => Category::find($id)]);
    }

    /**
     * Удаляем запись и возвращаем одну в конец списка
     *
     * @param $id
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        // Получаем запись
        $category = Category::find($id);

        // Ответ
        return response()->json(['success' => $category->delete()]);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    /**
     * Стриница категорий
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Получаем коллекцию категорий
        $categories = Category::withCount('posts')->get();

        return view('site.categories.index',
            compact('categories'));
    }

    /**
     * Страцица определенной категории
     * с постраничным выводом публикаций
     *
     * @param  \App\Category $category
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        // Получаем по 10 записей на страницу
        $posts = $category->posts()
                          ->orderBy('created_at', 'desk')
                          ->paginate(10);

        return view('site.categories.show', compact(['category', 'posts']));
    }
}

resources/views/site/categories/index.blade.php
@extends('layouts.site')

@section('title', 'Categories')

@section('content')
    <div class="card">
        <div class="card-header">All categories</div>

        <div class="card-body">
            <ul class="list-group">
                @foreach($categories as $category)
                    <li class="list-group-item">
                        <span class="mr-2">{{ $loop->iteration }}</span>

                        {{  link_to_route('categories.show', ($category->title ?? 'Untitled'), ['category' => $category]) }}

                        <span class="badge badge-pill badge-secondary">{{ $category->posts_count }}</span>
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
@endsection

resources/views/site/categories/show.blade.php
@extends('layouts.site')

@section('title',
 'Category - '
  . ($category->title ?? 'Untitled')
  . ($posts->lastPage() > 1 ? (' - page ' . $posts->currentPage()) : '')
)

@section('content')
    <div class="card">
        <div class="card-header">
            {{ link_to_route('categories.index', '<', null, ['class' => 'btn btn-secondary btn-sm mr-2']) }}

            {{ ($category->title ?? 'Untitled') }}

            @if($posts->lastPage() > 1)
                {{ ': ' . $posts->firstItem() . ' - ' . $posts->lastItem() }}
            @endif
        </div>

        <div class="card-body">
            <ul class="list-group mb-4">
                @forelse($posts as $post)
                    <li class="list-group-item">
                        <span class="mr-2">{{ $posts->firstItem() + $loop->index }}</span>
                        {{  link_to_route('posts.show', ($post->title ?? 'Untitled'), ['post' => $post], []) }}
                    </li>
                @empty
                    <li class="list-group-item">No posts</li>
                @endforelse
            </ul>

            {{ $posts->links() }}
        </div>
    </div>
@endsection