routes/web.php
<?php

// Сайт
Route::get('/', 'IndexController@index')->name('start');
Route::resource('posts', 'PostController')
     ->only(['index', 'show']);
Route::resource('categories', 'CategoryController')
     ->only(['index', 'show']);

// Админпанель
Route::group([
    'prefix'     => 'admin',
    'middleware' => 'auth',
    'namespace'  => 'Admin',
    'as'         => 'admin.',
], function () {
    Route::get('/', 'IndexController@index')->name('index');

    Route::get('posts', 'IndexController@posts')->name('posts.index');
    Route::get('posts/fetch', 'PostController@index');
    Route::resource('posts', 'PostController')
         ->only(['store', 'update', 'destroy']);

    Route::get('categories', 'IndexController@categories')->name('categories.index');
    Route::get('categories/fetch', 'CategoryController@index');
    Route::resource('categories', 'CategoryController')
         ->only(['store', 'update', 'destroy']);
});

// Авторизация
Auth::routes();
Route::match(['get', 'post'], '/register', function () {
    return redirect()->route('start');
})->name('register');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'content'];

    /**
     * Категории публикации
     * Связь many-to-many
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Post;

class PostController extends Controller
{

    /**
     * Получаем все записи постранично
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        // Получаем по 10 записей на страницу
        $posts      = Post::orderBy('created_at', 'desk')
                          ->with('categories')
                          ->paginate(20);
        // Получаем список категорий
        $categories = Category::all(['id', 'title']);

        // Ответ
        return response()->json([
            'posts'      => $posts,
            'categories' => $categories,
        ]);
    }

    /**
     * Создаем запись
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        // Создаем запись
        /** @var Post $post */
        $post = Post::create([
            'title'   => $request->input('title'),
            'content' => $request->input('content'),
        ]);

        // Привязываем категории
        $post->categories()->sync($request->input('categories'));

        // Ответ
        return response()->json(['post' => $post->load('categories')]);
    }

    /**
     * Обновляем запись
     *
     * @param \Illuminate\Http\Request $request
     * @param                          $id
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $id)
    {
        // Обновляем данные
        Post::find($id)->update([
            'title'   => $request->input('title'),
            'content' => $request->input('content'),
        ]);

        /** @var Post $post */
        $post = Post::find($id);

        // Привязываем категории
        $post->categories()->sync($request->input('categories'));

        // Ответ
        return response()->json(['post' => $post->load('categories')]);
    }

    /**
     * Удаляем запись
     *
     * @param $id
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        // Получаем запись
        $post = Post::find($id);

        // Ответ
        return response()->json(['success' => $post->delete()]);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{

    /**
     * Все публикации с постраничным выводом
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Получаем по 10 записей на страницу
        $posts = Post::orderBy('created_at', 'desk')
                     ->with('categories')
                     ->paginate(10);

        return view('site.posts.index', compact('posts'));


    }

    /**
     * Страница определенной публикации
     *
     * @param  \App\Post $post
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('site.posts.show',
            ['post' => $post->load('categories')]);
    }
}

resources/views/site/posts/index.blade.php
@extends('layouts.site')

@section('title',
'Posts'
 . ($posts->lastPage() > 1 ? (' - page ' . $posts->currentPage()) : '')
 )

@section('content')
    <div class="card">
        <div class="card-header">
            Posts

            @if($posts->lastPage() > 1)
                {{ ': ' . $posts->firstItem() . ' - ' . $posts->lastItem() }}
            @endif
        </div>

        <div class="card-body">
            <ul class="list-group mb-4">
                @forelse($posts as $post)
                    <li class="list-group-item">
                        <span class="mr-2">{{ $posts->firstItem() + $loop->index }}</span>
                        {{  link_to_route('posts.show', ($post->title ?? 'Untitled'), ['post' => $post]) }}
                    </li>
                @empty
                    <li class="list-group-item">No posts</li>
                @endforelse
            </ul>

            {{ $posts->links() }}
        </div>
    </div>
@endsection

resources/views/site/posts/show.blade.php
@extends('layouts.site')

@section('title', ('Post - ' . ($post->title ?? 'Untitled')))

@section('content')
    <div class="card">
        <div class="card-header">
            {{ link_to(url()->previous(), '<', ['class' => 'btn btn-secondary btn-sm mr-2']) }}
            Post - {{ $post->title ?? 'Untitled' }}
        </div>

        <div class="card-body">
            <p class="font-italic small">{{ $post->created_at }}</p>

            <p>
                @forelse($post->categories as $category)
                    {{ link_to_route('categories.show', ($category->title ?? 'Untitled'), ['category' => $category]) }}
                @empty
                    No categories
                @endforelse
            </p>

            <p>{{ $post->content }}</p>
        </div>
    </div>
@endsection